version: "3"
services:
  api:
    build: .
    ports:
      - 8010:8000
    volumes:
      - ./:/usr/src/app
    # env_file:
    #     - ./.env
    command: uvicorn src.main_withORM:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
